### ISSUE TITLE
Add ffmpeg for transcoding applications?

### ISSUE THREAD

**Issue by Andersama** [DvdGiessen/nginx-rtmp-docker#4]
Love how dirt simple this docker is, a lot of guides surrounding nginx configurations typically show a few examples of how to transcode (namely w/ ffmpeg). May be nice to have an include ffmpeg option. Thoughts?

There's a docker file for ffmpeg here https://github.com/jrottenberg/ffmpeg.

**Comment by eduncan911** [comment]
According to the source post that spawned this docker image, you can just add a single line for ffmpeg container wrapping for YouTube streams to the `nginx.conf` file:

https://obsproject.com/forum/threads/how-to-set-up-your-own-private-rtmp-server-using-nginx.12891/page-31#post-308773

As far as transcoding, I'd imagine you would modify the ffmpeg line as needed.
