### ISSUE TITLE
NEED-HELP: can't connect to stream

### ISSUE THREAD

**Issue by eduardogoncalves** [DvdGiessen/nginx-rtmp-docker#5]
Hi,
I'm trying to use your image. I installed IP Camera Lite, and can connect to rtmp server to stream iphone camera. I've tried a few different clients but I can't connect/access video stream, rtmp://192.168.1.103/live/stream/

Can someone help me stream iphone camera to this rtmp server and access it from another pc?

**Comment by DvdGiessen** [comment]
I'm not familiar with IP Camera Lite. How is the app configured to push to the server? Have you tried using an other app such as OBS to push a stream to the server with the same settings, and did that work for you?

**Comment by eduardogoncalves** [comment]
@DvdGiessen Thank you. I tried with OBS and it worked. At the iPhone 'IP Camera Lite' app, I've enable 'use software decoder', and disabled 'preferred h.264' and 'Use h.264 Hardware Decoder' and it's working know.

**Comment by DvdGiessen** [comment]
Glad you've solved it!
