### ISSUE TITLE
NEED HELP: Additional Dockerfile package installations are not available in the container

### ISSUE THREAD

**Issue by odedNea** [DvdGiessen/nginx-rtmp-docker#6]
Hi,
Thanks a lot for this image, it works really well for me!
I'm trying to install other packages such as ffmpeg:
`RUN apk add --no-cache \
    ffmpeg \
    build-base \
    libressl-dev `

When I try to use ffmpeg or ssh into the running container, ffmpeg is not found.
What am I doing wrong in my installation?

**Comment by DvdGiessen** [comment]
Hm, that should just work.

Can you share a complete copy of the Dockerfile you're using so I can try to reproduce the issue?

**Comment by odedNea** [comment]
Thanks for the quick reply!
I've figured that you're using multi-stage build, and to produce a smaller size image, you copy only the nginx to the newer image and I didn't copy mine.
I came up with a solution to install the ffmpeg package in the newer image (Didn't manage to copy it from the older to the newer).
Do you recommend copying the ffmpeg library/ies as you did with the nginx?

-Here is the copy of the Dockerfile:

\# Dockerfile for a simple Nginx stream replicator

\# Separate build stage to keep build dependencies out of our final image
ARG ALPINE_VERSION=alpine:3.8
FROM ${ALPINE_VERSION}

\# Software versions to build
ARG NGINX_VERSION=nginx-1.15.8
ARG NGINX_RTMP_MODULE_VERSION=6f5487ada9848a66cc7a3ed375e404fc95cc5302

\# Install buildtime dependencies
\# Note: We build against LibreSSL instead of OpenSSL, because LibreSSL is already included in Alpine
RUN apk --no-cache add \
    ffmpeg \
    build-base \
    libressl-dev 

\# Download sources
\# Note: We download our own fork of nginx-rtmp-module which contains some additional enhancements over the original version by arut
RUN mkdir -p /build && \
    wget -O - https://nginx.org/download/${NGINX_VERSION}.tar.gz | tar -zxC /build -f - && \
    mv /build/${NGINX_VERSION} /build/nginx && \
    wget -O - https://github.com/DvdGiessen/nginx-rtmp-module/archive/${NGINX_RTMP_MODULE_VERSION}.tar.gz | tar -zxC /build -f - && \
    mv /build/nginx-rtmp-module-${NGINX_RTMP_MODULE_VERSION} /build/nginx-rtmp-module

\# Build a minimal version of nginx
RUN cd /build/nginx && \
    ./configure \
        --build=DvdGiessen/nginx-rtmp-docker \
        --prefix=/etc/nginx \
        --sbin-path=/usr/local/sbin/nginx \
        --conf-path=/etc/nginx/nginx.conf \
        --error-log-path=/var/log/nginx/error.log \
        --http-log-path=/var/log/nginx/access.log \
        --pid-path=/var/run/nginx.pid \
        --lock-path=/var/lock/nginx.lock \
        --http-client-body-temp-path=/tmp/nginx/client-body \
        --user=nginx --group=nginx \
        --without-http-cache \
        --without-http_access_module \
        --without-http_auth_basic_module \
        --without-http_autoindex_module \
        --without-http_browser_module \
        --without-http_charset_module \
        --without-http_empty_gif_module \
        --without-http_fastcgi_module \
        --without-http_geo_module \
        --without-http_grpc_module \
        --without-http_gzip_module \
        --without-http_limit_conn_module \
        --without-http_limit_req_module \
        --without-http_map_module \
        --without-http_memcached_module \
        --without-http_mirror_module \
        --without-http_proxy_module \
        --without-http_referer_module \
        --without-http_rewrite_module \
        --without-http_scgi_module \
        --without-http_split_clients_module \
        --without-http_ssi_module \
        --without-http_upstream_hash_module \
        --without-http_upstream_ip_hash_module \
        --without-http_upstream_keepalive_module \
        --without-http_upstream_least_conn_module \
        --without-http_upstream_random_module \
        --without-http_upstream_zone_module \
        --without-http_userid_module \
        --without-http_uwsgi_module \
        --without-mail_imap_module \
        --without-mail_pop3_module \
        --without-mail_smtp_module \
        --without-pcre \
        --without-poll_module \
        --without-select_module \
        --without-stream_access_module \
        --without-stream_geo_module \
        --without-stream_limit_conn_module \
        --without-stream_map_module \
        --without-stream_return_module \
        --without-stream_split_clients_module \
        --without-stream_upstream_hash_module \
        --without-stream_upstream_least_conn_module \
        --without-stream_upstream_random_module \
        --without-stream_upstream_zone_module \
        --with-ipv6 \
        --add-module=/build/nginx-rtmp-module && \
    make -j $(getconf _NPROCESSORS_ONLN)

\# Final image stage
FROM ${ALPINE_VERSION}

\# Set up group and user
RUN addgroup -S nginx && \
    adduser -s /sbin/nologin -G nginx -S -D -H nginx

\# Set up directories
RUN mkdir -p /etc/nginx /var/log/nginx /var/www && \
    chown -R nginx:nginx /var/log/nginx /var/www && \
    chmod -R 775 /var/log/nginx /var/www

\# Forward logs to Docker
RUN ln -sf /dev/stdout /var/log/nginx/access.log && \
    ln -sf /dev/stderr /var/log/nginx/error.log

\# Set up exposed ports
EXPOSE 1935

\# Set up entrypoint
COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN chmod 555 /docker-entrypoint.sh
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD []

\# Copy files from build stage
COPY --from=0 /build/nginx/objs/nginx /usr/local/sbin/nginx
RUN chmod 550 /usr/local/sbin/nginx

\# Set up config file
COPY nginx.conf /etc/nginx/nginx.conf
RUN chmod 444 /etc/nginx/nginx.conf

**Comment by DvdGiessen** [comment]
Actually, you can build upon my existing Docker image. That should be a lot easier since you don't have to copy anything between stages.

```Dockerfile
# Use the latest version of nginx-rtmp-docker as a base
FROM dvdgiessen/nginx-rtmp-docker:latest

# Install ffmpeg
RUN apk --no-cache add ffmpeg
```

If you build this image and run it, it will now contain ffmpeg:
```
$ docker build -t mydockerimage .
Sending build context to Docker daemon  2.048kB
Step 1/2 : FROM dvdgiessen/nginx-rtmp-docker:latest
 ---> 000873c654b3
Step 2/2 : RUN apk --no-cache add ffmpeg
 ---> Using cache
 ---> acc90755c31c
Successfully built acc90755c31c
Successfully tagged mydockerimage:latest

$ docker run -ti --rm mydockerimage sh
/ # ffmpeg -version
ffmpeg version 3.4.4 Copyright (c) 2000-2018 the FFmpeg developers
built with gcc 6.4.0 (Alpine 6.4.0)
configuration: --prefix=/usr --enable-avresample --enable-avfilter --enable-gnutls --enable-gpl --enable-libass --enable-libmp3lame --enable-librtmp --enable-libvorbis --enable-libvpx --enable-libxvid --enable-libx264 --enable-libx265 --enable-libtheora --enable-libv4l2 --enable-postproc --enable-pic --enable-pthreads --enable-shared --enable-libxcb --disable-stripping --disable-static --enable-vaapi --enable-vdpau --enable-libopus --disable-debug
libavutil      55. 78.100 / 55. 78.100
libavcodec     57.107.100 / 57.107.100
libavformat    57. 83.100 / 57. 83.100
libavdevice    57. 10.100 / 57. 10.100
libavfilter     6.107.100 /  6.107.100
libavresample   3.  7.  0 /  3.  7.  0
libswscale      4.  8.100 /  4.  8.100
libswresample   2.  9.100 /  2.  9.100
libpostproc    54.  7.100 / 54.  7.100
/ #
```

**Comment by odedNea** [comment]
And if I have to change the nginx.conf file as well? :)

**Comment by DvdGiessen** [comment]
Similar, you can just copy over it:
```Dockerfile
# Use the latest version of nginx-rtmp-docker as a base
FROM dvdgiessen/nginx-rtmp-docker:latest

# Install ffmpeg
RUN apk --no-cache add ffmpeg

# Set up my own custom config file
COPY nginx.conf /etc/nginx/nginx.conf
RUN chmod 444 /etc/nginx/nginx.conf
```

Or when running the container, you can use a volume mapping to mount in your own custom config file:
```sh
$ docker run -dp 1935:1935 -v /path/to/my/custom/nginx.conf:/etc/nginx/nginx.conf mydockerimage
```

**Comment by odedNea** [comment]
Works!
Thanks a lot
